import type { QuizData } from './types';

export const QUIZ_CATEGORIES = ["Technical Knowledge", "Communication Skills", "Aptitude & Logical Reasoning"] as const;

export const quizData: QuizData = {
  "Technical Knowledge": {
    easy: [
      { question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "High Tech Modern Language", "Hyperlink and Text Markup Language", "Home Tool Markup Language"], correctAnswer: "Hyper Text Markup Language" },
      { question: "What does CSS stand for?", options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], correctAnswer: "Cascading Style Sheets" },
      { question: "Which is not a JavaScript data type?", options: ["Number", "String", "Boolean", "Float"], correctAnswer: "Float" },
      { question: "What tag is used to define an unordered list?", options: ["<ol>", "<li>", "<list>", "<ul>"], correctAnswer: "<ul>" },
      { question: "Which property is used to change the background color?", options: ["color", "bgcolor", "background-color", "background"], correctAnswer: "background-color" },
      { question: "How do you write a comment in JavaScript?", options: ["//This is a comment", "<!--This is a comment-->", "/* This is a comment */", "#This is a comment"], correctAnswer: "//This is a comment" },
      { question: "Which company developed JavaScript?", options: ["Microsoft", "Apple", "Netscape", "Sun Microsystems"], correctAnswer: "Netscape" },
      { question: "What is the correct HTML for creating a hyperlink?", options: ['<a href="url">link text</a>', '<a url="url">link text</a>', '<a>url</a>', '<link>url</link>'], correctAnswer: '<a href="url">link text</a>' },
      { question: "Which CSS property controls the text size?", options: ["font-style", "text-size", "font-size", "text-style"], correctAnswer: "font-size" },
      { question: "In DSA, what does 'FIFO' stand for?", options: ["First In, First Out", "First In, Fast Out", "Fast In, First Out", "First Index, First Out"], correctAnswer: "First In, First Out" },
    ],
    medium: [
      { question: "What is the 'box model' in CSS?", options: ["A model for 3D boxes", "A box that wraps every HTML element", "A model for laying out documents", "A model for text content"], correctAnswer: "A box that wraps every HTML element" },
      { question: "What is 'event delegation' in JavaScript?", options: ["Delegating events to a parent element", "Creating custom events", "Removing event listeners", "A design pattern for functions"], correctAnswer: "Delegating events to a parent element" },
      { question: "What is the difference between `==` and `===`?", options: ["No difference", "`===` compares type and value, `==` only value", "`==` is faster", "`===` is for numbers only"], correctAnswer: "`===` compares type and value, `==` only value" },
      { question: "What does 'git clone' do?", options: ["Creates a new branch", "Creates a copy of a remote repository", "Deletes a repository", "Merges two branches"], correctAnswer: "Creates a copy of a remote repository" },
      { question: "What is a 'closure' in JavaScript?", options: ["A function that has no access to its outer scope", "A function having access to its parent scope, even after the parent has closed", "A way to close memory leaks", "A type of variable"], correctAnswer: "A function having access to its parent scope, even after the parent has closed" },
      { question: "What is the purpose of the `alt` attribute on an `<img>` tag?", options: ["To provide alternative text if the image cannot be displayed", "To style the image", "To define the image source", "To make the image a link"], correctAnswer: "To provide alternative text if the image cannot be displayed" },
      { question: "What is a Stack in DSA?", options: ["A LIFO data structure", "A FIFO data structure", "A tree-based structure", "A graph-based structure"], correctAnswer: "A LIFO data structure" },
      { question: "What is the CSS `display: flex` used for?", options: ["To create a flexible layout model", "To display text", "To hide an element", "To animate an element"], correctAnswer: "To create a flexible layout model" },
      { question: "How do you select an element with id 'demo' in CSS?", options: [".demo", "demo", "#demo", "*demo"], correctAnswer: "#demo" },
      { question: "What is a 'promise' in JavaScript?", options: ["An object representing the eventual completion or failure of an asynchronous operation", "A guarantee that a function will run", "A callback function", "A synchronous function"], correctAnswer: "An object representing the eventual completion or failure of an asynchronous operation" },
    ],
    hard: [
      { question: "Explain the concept of 'hoisting' in JavaScript.", options: ["Moving all declarations to the top of the current scope", "A way to lift variables into the global scope", "A performance optimization technique", "A type of error"], correctAnswer: "Moving all declarations to the top of the current scope" },
      { question: "What is the Big O notation for a binary search algorithm?", options: ["O(n)", "O(log n)", "O(n^2)", "O(1)"], correctAnswer: "O(log n)" },
      { question: "What are CSS Specificity rules?", options: ["Rules that decide which CSS property values are most relevant to an element", "Rules for specific browsers", "Rules for specific devices", "Rules for naming CSS classes"], correctAnswer: "Rules that decide which CSS property values are most relevant to an element" },
      { question: "What is a 'pure function'?", options: ["A function with no side-effects and its return value is the same for the same arguments", "A function that returns a boolean", "A function that uses promises", "A function that is part of a class"], correctAnswer: "A function with no side-effects and its return value is the same for the same arguments" },
      { question: "What is the difference between `let`, `const`, and `var`?", options: ["`let` and `const` are block-scoped, `var` is function-scoped", "They are all the same", "`const` is for constants, `let` and `var` are for variables", "`var` is deprecated"], correctAnswer: "`let` and `const` are block-scoped, `var` is function-scoped" },
      { question: "What is a 'higher-order component' in React?", options: ["A component that renders other components", "A function that takes a component and returns a new component", "A component that is at the top of the component tree", "A component with complex state"], correctAnswer: "A function that takes a component and returns a new component" },
      { question: "What is Tree Traversal?", options: ["The process of visiting each node in a tree data structure", "A method to balance a tree", "A search algorithm for trees", "A way to delete nodes from a tree"], correctAnswer: "The process of visiting each node in a tree data structure" },
      { question: "What are Service Workers?", options: ["Scripts that run in the background, separate from a web page", "Workers in a server farm", "A type of web hosting", "A JavaScript library for services"], correctAnswer: "Scripts that run in the background, separate from a web page" },
      { question: "What is the Event Loop in JavaScript?", options: ["A mechanism that allows Node.js to perform non-blocking I/O operations", "A loop that listens for DOM events", "A `for` loop for events", "A way to create custom events"], correctAnswer: "A mechanism that allows Node.js to perform non-blocking I/O operations" },
      { question: "What is memoization?", options: ["An optimization technique used to reduce redundant calculations", "A way to store data in memory", "A type of recursion", "A design pattern for caching"], correctAnswer: "An optimization technique used to reduce redundant calculations" },
    ],
  },
  "Communication Skills": {
    easy: [
      { question: "What is a key component of active listening?", options: ["Waiting for your turn to speak", "Providing feedback and asking clarifying questions", "Interrupting to share your opinion", "Thinking about your response while the other person is talking"], correctAnswer: "Providing feedback and asking clarifying questions" },
      { question: "Which of these is a form of non-verbal communication?", options: ["Email", "Text message", "Body language", "Phone call"], correctAnswer: "Body language" },
      { question: "What is empathy?", options: ["Feeling sorry for someone", "The ability to understand and share the feelings of another", "Agreeing with someone's opinion", "Giving advice"], correctAnswer: "The ability to understand and share the feelings of another" },
      { question: "A 'you' statement in a conflict often sounds...", options: ["Supportive", "Accusatory", "Neutral", "Empathetic"], correctAnswer: "Accusatory" },
      { question: "What does it mean to be concise?", options: ["Using complex vocabulary", "Speaking for a long time", "Giving a lot of information in a few words", "Being loud and clear"], correctAnswer: "Giving a lot of information in a few words" },
      { question: "What is the purpose of an 'open-ended question'?", options: ["To get a 'yes' or 'no' answer", "To encourage a detailed response", "To confuse the listener", "To end a conversation"], correctAnswer: "To encourage a detailed response" },
      { question: "What is constructive feedback?", options: ["Criticism that is meant to hurt", "Feedback that is vague and unhelpful", "Feedback that is specific, actionable, and intended to help", "Praise without any suggestions"], correctAnswer: "Feedback that is specific, actionable, and intended to help" },
      { question: "What is a common barrier to effective communication?", options: ["Clear language", "Active listening", "Emotional distractions", "Mutual respect"], correctAnswer: "Emotional distractions" },
      { question: "In written communication, what does 'tone' refer to?", options: ["The font size", "The volume of the words", "The attitude or feeling conveyed by the words", "The color of the text"], correctAnswer: "The attitude or feeling conveyed by the words" },
      { question: "What is the first step in resolving a conflict?", options: ["Ignoring the problem", "Blaming the other person", "Acknowledging that a conflict exists", "Seeking a mediator"], correctAnswer: "Acknowledging that a conflict exists" },
    ],
    medium: [
      { question: "What is the 'feedback sandwich' technique?", options: ["A method for delivering negative feedback between two pieces of positive feedback", "A way to avoid giving feedback", "A type of team-building exercise", "A communication model for presentations"], correctAnswer: "A method for delivering negative feedback between two pieces of positive feedback" },
      { question: "What is the difference between assertive and aggressive communication?", options: ["Assertive is passive, aggressive is active", "Assertive expresses needs respectfully, aggressive is hostile and demanding", "There is no difference", "Assertive is for leaders, aggressive is for followers"], correctAnswer: "Assertive expresses needs respectfully, aggressive is hostile and demanding" },
      { question: "What is the '5 W's' method used for in communication?", options: ["To ask questions in an interview", "To structure a story or report (Who, What, When, Where, Why)", "A negotiation tactic", "A public speaking technique"], correctAnswer: "To structure a story or report (Who, What, When, Where, Why)" },
      { question: "How can you build rapport with someone you've just met?", options: ["Talk only about yourself", "Find common interests and practice active listening", "Avoid eye contact", "Challenge their opinions immediately"], correctAnswer: "Find common interests and practice active listening" },
      { question: "In a business context, what is an 'elevator pitch'?", options: ["A long, detailed presentation", "A request for a promotion in an elevator", "A short, persuasive speech to spark interest in a project or idea", "A technical manual"], correctAnswer: "A short, persuasive speech to spark interest in a project or idea" },
      { question: "What is a potential downside of using jargon?", options: ["It can exclude or confuse people who are not familiar with the terms", "It makes you sound more intelligent", "It is always clear and concise", "It is universally understood"], correctAnswer: "It can exclude or confuse people who are not familiar with the terms" },
      { question: "What is the 'mirroring' technique in communication?", options: ["Copying someone's accent", "Repeating the last few words someone said", "Subtly mimicking another person's non-verbal cues to build rapport", "Looking at yourself in a mirror while speaking"], correctAnswer: "Subtly mimicking another person's non-verbal cues to build rapport" },
      { question: "How can storytelling be an effective communication tool?", options: ["It can make information more memorable and engaging", "It is only useful for entertaining children", "It is unprofessional in a business setting", "It complicates simple messages"], correctAnswer: "It can make information more memorable and engaging" },
      { question: "What is the importance of a clear call-to-action (CTA)?", options: ["It is not important", "It tells the audience what you want them to do next", "It is a summary of your message", "It is a legal requirement"], correctAnswer: "It tells the audience what you want them to do next" },
      { question: "What is 'groupthink'?", options: ["A collaborative brainstorming technique", "A psychological phenomenon where the desire for harmony in a group results in an irrational decision-making outcome", "The collective intelligence of a group", "A project management methodology"], correctAnswer: "A psychological phenomenon where the desire for harmony in a group results in an irrational decision-making outcome" },
    ],
    hard: [
      { question: "Explain the 'Johari Window' model.", options: ["A model for time management", "A technique for self-awareness and mutual understanding between individuals", "A framework for project planning", "A tool for financial analysis"], correctAnswer: "A technique for self-awareness and mutual understanding between individuals" },
      { question: "Describe the 'SCARF' model in the context of collaboration and influence.", options: ["A model for remembering names", "A model of social domains that drive human behavior (Status, Certainty, Autonomy, Relatedness, Fairness)", "A safety protocol for labs", "A software development lifecycle model"], correctAnswer: "A model of social domains that drive human behavior (Status, Certainty, Autonomy, Relatedness, Fairness)" },
      { question: "What is the difference between a high-context and a low-context culture in communication?", options: ["High-context relies on explicit verbal communication, low-context relies on non-verbal cues", "Low-context relies on explicit verbal communication, high-context relies on non-verbal cues and context", "There is no difference", "It relates to the technological advancement of a culture"], correctAnswer: "Low-context relies on explicit verbal communication, high-context relies on non-verbal cues and context" },
      { question: "What is 'paralanguage'?", options: ["A formal, written language", "The non-lexical component of communication by speech, for example, intonation, pitch and speed of speaking", "A secret code language", "The language used by parrots"], correctAnswer: "The non-lexical component of communication by speech, for example, intonation, pitch and speed of speaking" },
      { question: "In negotiation, what is a 'BATNA'?", options: ["Best Alternative To a Negotiated Agreement", "Basic Agreement on Terms and Negotiations", "The initial offer in a negotiation", "A type of legal contract"], correctAnswer: "Best Alternative To a Negotiated Agreement" },
      { question: "How does cognitive bias, such as 'confirmation bias', affect communication?", options: ["It helps to make communication more objective", "It causes us to favor information that confirms our existing beliefs, leading to poor listening and decision-making", "It improves the speed of communication", "It has no effect on communication"], correctAnswer: "It causes us to favor information that confirms our existing beliefs, leading to poor listening and decision-making" },
      { question: "What is the role of silence in a conversation?", options: ["It always indicates disagreement", "It has no role and should be avoided", "It can be used to emphasize a point, show thoughtfulness, or create tension", "It is a sign of poor communication skills"], correctAnswer: "It can be used to emphasize a point, show thoughtfulness, or create tension" },
      { question: "What is the 'Pygmalion Effect' in interpersonal communication?", options: ["The phenomenon where higher expectations lead to an increase in performance", "The tendency to over-communicate", "A fear of public speaking", "A linguistic theory about language origins"], correctAnswer: "The phenomenon where higher expectations lead to an increase in performance" },
      { question: "What are the key differences between synchronous and asynchronous communication?", options: ["Synchronous is written, asynchronous is spoken", "Synchronous happens in real-time (e.g., phone call), asynchronous is delayed (e.g., email)", "Asynchronous is faster", "There is no difference"], correctAnswer: "Synchronous happens in real-time (e.g., phone call), asynchronous is delayed (e.g., email)" },
      { question: "How would you handle a situation where you need to communicate a complex technical concept to a non-technical audience?", options: ["Use as much technical jargon as possible to sound smart", "Avoid the topic altogether", "Use analogies, simple language, and focus on the 'why' and 'what' rather than the 'how'", "Send them a technical manual to read"], correctAnswer: "Use analogies, simple language, and focus on the 'why' and 'what' rather than the 'how'" },
    ],
  },
  "Aptitude & Logical Reasoning": {
    easy: [
      { question: "If a train travels 60 miles in 1 hour, how many miles will it travel in 2.5 hours?", options: ["120 miles", "150 miles", "180 miles", "100 miles"], correctAnswer: "150 miles" },
      { question: "Which number is the odd one out? 2, 4, 6, 7, 8, 10", options: ["4", "6", "7", "8"], correctAnswer: "7" },
      { question: "If 'pen' is to 'write', then 'needle' is to...", options: ["Sew", "Knit", "Thread", "Point"], correctAnswer: "Sew" },
      { question: "What is the next number in the series: 2, 5, 8, 11, __?", options: ["12", "13", "14", "15"], correctAnswer: "14" },
      { question: "A man is walking north. He turns left, then left again. In which direction is he walking now?", options: ["North", "South", "East", "West"], correctAnswer: "South" },
      { question: "If 5 cats can catch 5 mice in 5 minutes, how many cats are needed to catch 100 mice in 100 minutes?", options: ["100", "50", "10", "5"], correctAnswer: "5" },
      { question: "Find the average of 10, 20, and 30.", options: ["15", "20", "25", "60"], correctAnswer: "20" },
      { question: "A book is to a library as a tree is to a...", options: ["Forest", "Leaf", "Branch", "Root"], correctAnswer: "Forest" },
      { question: "What is 25% of 200?", options: ["25", "40", "50", "75"], correctAnswer: "50" },
      { question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctAnswer: "6" },
    ],
    medium: [
      { question: "A is the father of B. But B is not A's son. What is the relationship between A and B?", options: ["A is B's uncle", "B is A's daughter", "B is A's nephew", "No relation"], correctAnswer: "B is A's daughter" },
      { question: "A clock shows the time as 3:15. What is the angle between the hour and minute hands?", options: ["0 degrees", "5 degrees", "7.5 degrees", "10 degrees"], correctAnswer: "7.5 degrees" },
      { question: "If the price of an item is increased by 20% and then decreased by 20%, what is the net change?", options: ["0% change", "4% increase", "4% decrease", "2% decrease"], correctAnswer: "4% decrease" },
      { question: "What is the next number in the series: 1, 4, 9, 16, 25, __?", options: ["30", "36", "49", "64"], correctAnswer: "36" },
      { question: "A man buys an article for $27.50 and sells it for $28.60. Find his gain percent.", options: ["3%", "4%", "5%", "6%"], correctAnswer: "4%" },
      { question: "In a group of 60 people, 40 speak Hindi, 25 speak both English and Hindi. Everyone speaks at least one language. How many speak only English?", options: ["20", "25", "30", "45"], correctAnswer: "20" },
      { question: "The day before yesterday was Saturday. What day will it be the day after tomorrow?", options: ["Tuesday", "Wednesday", "Thursday", "Friday"], correctAnswer: "Wednesday" },
      { question: "If 'CAT' is coded as 24, what is the code for 'DOG'?", options: ["26", "27", "28", "29"], correctAnswer: "26" },
      { question: "A mother is twice as old as her son. If 20 years ago, the age of the mother was 10 times the age of the son, what is the present age of the mother?", options: ["38 years", "40 years", "43 years", "45 years"], correctAnswer: "45 years" },
      { question: "If a dozen eggs cost $1.80, how much would 8 eggs cost?", options: ["$1.00", "$1.20", "$1.40", "$1.50"], correctAnswer: "$1.20" },
    ],
    hard: [
      { question: "Two trains are on the same track a distance 100 km apart. Train A starts towards train B at 50 km/h, and train B starts towards train A at 50 km/h. A bird starts at train A, flies to train B, then back to A, and so on, at 100 km/h. What is the total distance the bird flies before the trains collide?", options: ["50 km", "100 km", "150 km", "200 km"], correctAnswer: "100 km" },
      { question: "There are 8 balls, one of which is slightly heavier. Using a balance scale, what is the minimum number of weighings to find the heavy ball?", options: ["1", "2", "3", "4"], correctAnswer: "2" },
      { question: "If you have a 3-gallon jug and a 5-gallon jug, how can you measure out exactly 4 gallons of water?", options: ["Fill 5, pour to 3, empty 3, pour rest from 5 to 3, fill 5, pour to 3", "Fill 3, pour to 5, fill 3, pour to 5, empty 5, pour rest from 3 to 5", "It's impossible", "Fill 3, empty it, fill 5, pour to 3"], correctAnswer: "Fill 5, pour to 3, empty 3, pour rest from 5 to 3, fill 5, pour to 3" },
      { question: "What is the next number in the sequence: 77, 49, 36, 18, __?", options: ["8", "12", "10", "9"], correctAnswer: "8" },
      { question: "A man has 53 socks in his drawer: 21 identical blue, 15 identical black and 17 identical red. The lights are out. How many socks must he take out to be 100% certain he has a pair of black socks?", options: ["4", "21", "38", "40"], correctAnswer: "40" },
      { question: "A cube is painted red on all sides. It is then cut into 64 smaller cubes of equal size. How many cubes have no faces painted?", options: ["4", "8", "16", "24"], correctAnswer: "8" },
      { question: "Statements: All pens are pencils. No pencil is a book. Conclusions: I. No pen is a book. II. Some pencils are pens.", options: ["Only I follows", "Only II follows", "Both I and II follow", "Neither I nor II follows"], correctAnswer: "Both I and II follow" },
      { question: "If in a certain language, 'Madras' is coded as 'Nbesbt', how is 'Bombay' coded?", options: ["Cpncpz", "Cpncqx", "Cpnacz", "Cpmcbz"], correctAnswer: "Cpncpz" },
      { question: "A, B, C, D, E, F are sitting in a circle. A is between E and F. E is opposite D, and C is not in either of the neighboring seats of E. Who is opposite B?", options: ["A", "C", "F", "D"], correctAnswer: "F" },
      { question: "What is the probability of getting a sum of 7 when two dice are thrown?", options: ["1/6", "1/12", "1/36", "7/36"], correctAnswer: "1/6" },
    ],
  },
};
